# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
  - script: dir
    workingDirectory: $(Build.SourcesDirectory)
    displayName: List contents of a BuildDirectory
