# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: VCPKG_BINARY_SOURCES
  value: 'clear;nuget,https://azfunc.pkgs.visualstudio.com/e6a70c92-4128-439f-8012-382fe78d6396/_packaging/FunctionsNetHostBinaryCache/nuget/v3/index.json,readwrite'
- name: VCPKG_USE_NUGET_CACHE
  value: 1

trigger:
- master

pool:
  vmImage: windows-latest

steps:
  # Remember to add this task to allow vcpkg to upload archives via NuGet
  - task: NuGetAuthenticate@1
    inputs:
      nuGetServiceConnections: 'FuncNetHostBinaryCacheVcPkgNugetPush'
      forceReinstallCredentialProvider: true

  - script: dir
    workingDirectory: $(Build.SourcesDirectory)
    displayName: List contents of a BuildDirectory
  - task: CMake@1
    displayName: 'CMake ..'
    inputs:
      cmakeArgs: '-S $(Build.SourcesDirectory) -B $(Build.SourcesDirectory)/build'
  - task: CMake@1
    displayName: 'CMake --build . --config Release'
    inputs:
      cmakeArgs: '--build $(Build.SourcesDirectory)/build --config Release --verbose'
 
  - script: dir
    workingDirectory: $(Build.SourcesDirectory)/build/SubModule1/Release
    displayName: List Release Artifacts

  - publish: $(Build.SourcesDirectory)/build/SubModule1/Release
    artifact: drop